config/routes.rb
Curso::Application.routes.draw do

  resources :users do
    member do
      get :profile
    end
  end
  
  resources :session

  resources :books do
    member do
      patch :read 
    end
    resources :comments
  end

  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :comments

  has_and_belongs_to_many :users

  def read_by_user?(user)
    users.include?(user)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :book
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user

  validates :zip_code, presence: true
  validate :zip

  private

  def zip
    errors.add(:zip_code, "El zip debe ser par") unless zip_code.even?
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :profile, dependent: :destroy #nullify
  has_many :comments

  has_and_belongs_to_many :books

  accepts_nested_attributes_for :profile

  #Validaciones

  validates :last_name, :email, presence: true

  def self.ordenado_por_nombre
    order('name ASC')
  end

  def self.authenticate(email, password)
    u = User.where(email: email).first
    
    if u.nil?
      return nil 
    elsif u.password != password
      return nil
    else
      return u
    end
  end

  def nombre_completo
    [name, last_name].join(" ")
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :auth! 

  def current_user
    User.find(session[:user])
  end

  def auth!
    unless session[:user]
      redirect_to new_session_path, notice: "Debe estar logeado"
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :read?, only: :read
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])

    @read = @book.read_by_user?(current_user)
  end

  def new
    @book = Book.new
  end

  def create
    if Book.create(permit_params)
      flash[:notice] = "El Book se ha creado con exito"
      redirect_to books_path
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(permit_params)
      flash[:notice] = "El book se ha actualizado correctamente"
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = "El book se ha borrado correctamente"
      redirect_to books_path
    end
  end

  def read
    book = Book.find(params[:id])
    
    book.users << current_user

    redirect_to book_path(book), notice: "Enhorabuena, ya habeís leido el libro."
  end

  private

  def permit_params
    params.require(:book).permit!
  end

  def read?
    book = Book.find(params[:id])

    if book.read_by_user?(current_user)
      redirect_to book_path(book), notice: "Ya habeís leido el libro."
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @book = Book.find(params[:book_id])
    @comment = @book.comments.build
  end

  def create
    @book = Book.find(params[:book_id])
    @comment = Comment.new(permit_params)
    @comment.user = current_user
    @comment.book_id = params[:book_id]
    if @comment.save
      flash[:notice] = "El comentario fue creado correctamente"
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  private

  def permit_params
    params.require(:comment).permit!
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  skip_before_action :auth!

  def new
    sleep 30
  end

  def create
    user = User.authenticate(params[:user][:email], params[:user][:password])

    unless user.nil?
      session[:user] = user.id
      redirect_to root_url, notice: "Sesion iniciada"
    end
  end

  def destroy
    session[:user] = nil

    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.ordenado_por_nombre
  end

  def new
    @user = User.new
    @user.build_profile
  end

  def create
    @user = User.new(permit_params)
    if @user.save
      flash[:notice] = "Usuario Creado con Exito"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(permit_params)
      flash[:notice] = "Usuario Actualizado con Exito"
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "El usuario fue eliminado correctamente"
      redirect_to users_path
    end
  end

  def profile
    @profile = User.find(params[:id]).profile
  end

  private

  def permit_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= semantic_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :publish_date, as: :string %>
  <%= f.input :page_count %>
  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form" %>

app/views/books/index.html.erb
<h3><%= flash[:notice] %></h3>

<h1>Books</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publish Date</th>
      <th>Page Count</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title%></td>
      <td><%= book.author %></td>
      <td><%= book.publish_date %></td>
      <td><%= book.page_count %></td>
      <td><%= book.created_at %></td>
      <td><%= book.updated_at %></td>
      <td>
        <%= link_to "Ver Libro", book_path(book) %>
        <%= link_to "Editar", edit_book_path(book) %>
        <%= link_to "Eliminar", book_path(book), method: :delete, data: { confirm: "¿Está seguro?" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</br>
<%= link_to "Create Book", new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render "form" %>

app/views/books/show.html.erb
<%= flash[:notice] %>

<h1>Libro: <%= @book.title %></h1>
<p>
  <b>Author: </b>
  <%= @book.author %>
  <% unless @read %>
    <%= link_to "Ya lo lei", read_book_path, method: :patch %>
  <% end  %>
</p>
</br>

<table border = "1">
  <thead>
    <tr>
      <th>Usuario</td>
      <th>Comentario</td>
    </tr>
  </thead>
  <tbody>
    <% @book.comments.each do |comment| %>
      <tr>
        <td><%= comment.user.nombre_completo %></td>
        <td><%= comment.comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Read by: </h3>

<% @book.users.each do |user| %>
  <b><%= user.nombre_completo %></b>
<% end %>

</br>
</br>
<%= link_to "Crear Comentario", new_book_comment_path(@book) %>

app/views/comments/new.html.erb
<h1>Crear comentario para: <%= @book.title %></h1>

<%= semantic_form_for [@book, @comment] do |f| %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Este es un titulo</title>
  <%= stylesheet_link_tag  "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- session_path(1) es un force para el destroy. -->
<%= link_to "Logout", session_path(1), method: :delete %>
</br></br>
<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<%= flash[:notice] %>

<h3>Inicio de Sesión: </h3>

<%= semantic_form_for :user, url: "/session", method: :post do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.submit "Logear" %>
<% end %>

app/views/users/_form.html.erb
<h2>Errores: </h2>
<% @user.errors.messages.each do |key,value| %>
  <p>
    <b><%= key.to_s.humanize %>:</b>
    <%= value.first %>
  </p>
<% end %>

<%= semantic_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :birth_day, as: :string, label: "Fecha de Nacimiento" %>
  <%= f.input :password %>

  <h3>Profile:</h3>
  
  <%= f.semantic_fields_for :profile do |h| %>
    <%= h.input :phone %>
    <%= h.input :country, as: :string %>
    <%= h.input :city %>
    <%= h.input :zip_code %>
    <%= h.input :line1 %>
    <%= h.input :line2 %>
    <%= h.input :url_gravatar %>
  <% end %>

  <h3>Libros: </h3>

  <%= f.input :books, as: :check_boxes %>

  </br>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Editar Usuario</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h3><%= flash[:notice] %></h3>

<h1>Users</h1>

<table border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Birthday</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.birth_day %></td>
      <td><%= user.created_at %></td>
      <td><%= user.updated_at %></td>
      <td>
        <%= link_to "Editar", edit_user_path(user) %>
        <%= link_to "Eliminar", user_path(user), method: :delete, data: { confirm: "¿Está seguro?" } %>
        <%= link_to "Ver Profile", profile_user_path(user) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

</br>

<%= link_to "Create User", new_user_path %>

app/views/users/new.html.erb
<h1>Nuevo Usuario</h1>

<%= render "form" %>

app/views/users/profile.html.erb
<h1>Profile de: <%= @profile.user.nombre_completo %></h1>

<p>
  <b>Phone: </b>
  <%= @profile.phone %>
</p>
<p>
  <b>Country: </b>
  <%= @profile.country %>
</p>
<p>
  <b>City: </b>
  <%= @profile.city %>
</p>
<p>
  <b>Zip Code: </b>
  <%= @profile.zip_code %>
</p>